name: Terraform Init, Validate, Plan and Comment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true
      working-directory:
        description: 'Directory containing Terraform configuration'
        type: string
        required: true
      skip-comment:
        description: 'Skip commenting on the PR'
        type: boolean
        required: false
        default: false


permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  init-validate-plan-comment:
    name: Terraform Init, Validate, Plan and Comment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ inputs.working-directory }}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ${{ inputs.working-directory }}
        run: |
          terraform plan \
            -no-color \
            -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Check for Plan Errors
        working-directory: ${{ inputs.working-directory }}
        run: |
          if grep -q "Error:" plan.txt; then
            echo "Terraform plan contains errors"
            exit 1
          fi

      - name: Comment Plan on PR
        uses: mshick/add-pr-comment@v2
        if: ${{ inputs.skip-comment != 'true' }}
        with:
          message-path: ${{ inputs.working-directory }}/plan.txt
          repo-token: ${{ secrets.GITHUB_TOKEN }}
