name: Run Terraform Plan

on:
  workflow_dispatch:
  # Remove workflow_dispatch and uncomment the following lines to enable automatic triggering on push events
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - '**/*.tf'
  #     - '**/*.tfvars'
  # Uncomment the following lines to enable automatic triggering on pull request events

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Plan, Validate, and Comment for the main environment
    uses: ./.github/workflows/terraform-init-validate-plan-comment.yml
    with:
      working-directory: 'environments/main'
      var-file-path: 'config/projects.tfvars'
    secrets: inherit