name: Run Terraform Plan

on:
  workflow_dispatch:
  # Remove workflow_dispatch and uncomment the following lines to enable automatic triggering on push events
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - '**/*.tf'
  #     - '**/*.tfvars'
  # Uncomment the following lines to enable automatic triggering on pull request events

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan-dev:
    name: Dev - Terraform Plan, Validate, and Comment
    uses: ./.github/workflows/terraform-init-validate-plan-comment.yml
    with:
      environment: 'dev'
      working-directory: 'environments/dev'
    secrets: inherit

  terraform-plan-prod:
    name: Prod - Terraform Plan, Validate, and Comment
    uses: ./.github/workflows/terraform-init-validate-plan-comment.yml
    with:
      environment: 'prod'
      working-directory: 'environments/prod'
    secrets: inherit