name: Run Terraform Plan

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan-dev:
    name: Dev - Terraform Plan, Validate, and Comment
    uses: ./.github/workflows/terraform-init-validate-plan-comment.yml
    with:
      environment: 'dev'
      working-directory: 'environments/dev'
    secrets: inherit

  terraform-plan-prod:
    name: Prod - Terraform Plan, Validate, and Comment
    uses: ./.github/workflows/terraform-init-validate-plan-comment.yml
    with:
      environment: 'prod'
      working-directory: 'environments/prod'
    secrets: inherit